PROJECT=tax_appeal
BLUE=\033[0;34m
NC=\033[0m # No Color

dev-setup-llm:
	@echo "\n${BLUE}Install required python packages${NC}\n"
	@pip install --upgrade -r dev-requirements.txt
.PHONY: dev-setup-llm
